const black = 0;
const white = 255;

const dit = 5;
const dah = 3 * dit;
const symbolSpace = dit;
const letterSpace = dah;
const wordSpace = 7 * dit;

const counter = [
  dah,
  dah + symbolSpace,
  dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + symbolSpace + dah,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace,
  dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + symbolSpace + dah + letterSpace + dah + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dah + symbolSpace + dah + letterSpace + dit + symbolSpace + dah + letterSpace + dah + letterSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + symbolSpace + dit + symbolSpace + dit + letterSpace + dit + wordSpace + dit + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + symbolSpace + dit + letterSpace + dit + symbolSpace + dah + symbolSpace + dit + letterSpace + dit + wordSpace + dah + symbolSpace + dit + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dit + symbolSpace + dah + letterSpace + dah + wordSpace + dah + letterSpace + dit + symbolSpace + dit + letterSpace + dah + symbolSpace + dah + letterSpace + dit + letterSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace + dit + symbolSpace + dah + symbolSpace + dah
];

let index = 0;
let countStart = 0;

function setup() {
  createCanvas(windowWidth, windowHeight);
}

function touchStarted() {
  if (!fullscreen()) {
    fullscreen(true);
  }
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

document.ontouchmove = function (event) {
  event.preventDefault();
};

function draw() {
  frameRate(60);
  if (frameCount >= countStart + counter[index]) {
    index++;

    if ((index - 1) % 2 === 0) {
      background(white);
    } else {
      background(black);
    }

    if (index >= counter.length) {
      index = 0;
      countStart = frameCount;
    }

    decode();
  }
}

function decode() {
  if (index === 1) { console.log('NO') }
  if (index === 10) { console.log('MORE') }
  if (index === 28) { console.log('WATER,') }
  if (index === 60) { console.log('THE') }
  if (index === 72) { console.log('FIRE') }
  if (index === 92) { console.log('NEXT') }
  if (index === 108) { console.log('TIME!') }
}
